### ISSUE TITLE
Blob demo now crashes

### ISSUE THREAD

**Issue by pdesaulniers** [poke1024/tove2d#18]
Here's the GDB backtrace:
```
Thread 1 "love" received signal SIGSEGV, Segmentation fault.
0x00007ffff0707d8d in tove::BestGradientColors::enabled (r=0x0) at src/cpp/../thirdparty/nanosvg/src/../tove/svgrast.cpp:237
237			return r->quality > 0;

INSERT (gdb) bt
#0  0x00007ffff0707d8d in tove::BestGradientColors::enabled (r=0x0) at src/cpp/../thirdparty/nanosvg/src/../tove/svgrast.cpp:237
#1  0x00007ffff070592a in tove::tove__initPaint (cache=0x7fffffffd650, r=0x0, paint=0x7fffffffdb00, opacity=1, initCacheColors=@0x7fffffffd5b3: false) at src/cpp/../thirdparty/nanosvg/src/../tove/svgrast.cpp:411
#2  0x00007ffff0704ba8 in tove::nsvg__initPaint (cache=0x7fffffffd650, paint=0x7fffffffdb00, opacity=1, r=0x0, scanline=0x0) at src/cpp/../thirdparty/nanosvg/src/nanosvgrast.h:1173
#3  0x00007ffff070669a in tove::nsvg::CachedPaint::init (this=0x7fffffffdb10, paint=..., opacity=1) at src/cpp/nsvg.cpp:388
#4  0x00007ffff06da3b5 in tove::AbstractPaintFeed::update (this=0x5555567ab668, paint=std::shared_ptr<tove::AbstractPaint> (use count 1, weak count 0) = {...}, opacity=1) at src/cpp/interface/../shader/feed/paint_feed.h:141
#5  0x00007ffff06da970 in tove::PaintFeedBase::bind (this=0x5555567ab660, data=..., i=1) at src/cpp/interface/../shader/feed/paint_feed.h:232
#6  0x00007ffff06daef9 in tove::ColorFeed::bind (this=0x555556965530, data=...) at src/cpp/interface/../shader/feed/color_feed.h:69
#7  0x00007ffff06d7786 in FeedBind (link=..., data=0x400e2330) at src/cpp/interface/api.cpp:709
#8  0x00007ffff7a2ca9b in ?? () from /usr/lib/libluajit-5.1.so.2
#9  0x00007ffff7a64510 in ?? () from /usr/lib/libluajit-5.1.so.2
#10 0x00007ffff7a64ddb in ?? () from /usr/lib/libluajit-5.1.so.2
#11 0x00007ffff7a2a916 in ?? () from /usr/lib/libluajit-5.1.so.2
#12 0x00007ffff7a70780 in ?? () from /usr/lib/libluajit-5.1.so.2
#13 0x00007ffff7a2a916 in ?? () from /usr/lib/libluajit-5.1.so.2
#14 0x0000555555555295 in ?? ()
#15 0x00007ffff7882223 in __libc_start_main () from /usr/lib/libc.so.6
#16 0x00005555555554ce in ?? ()

```

**Comment by pdesaulniers** [comment]
OK, seems fixed.
